### ISSUE TITLE
"Create C# Solution" button crashes godot

### ISSUE THREAD

**Issue by ghost** [neikeq/GodotSharp#46]
with the error

```
ERROR: operator[]: FATAL: Index p_index out of size (size()).
   At: core/vector.h:137.
```

Here's the backtrace
https://pastebin.com/xT99AGmf

**Comment by neikeq** [comment]
Is this on latest master? I thought I already fixed this with a deferred call to `remove_item`.

**Comment by ghost** [comment]
Yes, both godot and godotsharp were compiled from the latest master.

**Comment by neikeq** [comment]
Does this still happen after e5d5bd4?

**Comment by ghost** [comment]
I can't seem to be build it anymore (with or without mono_glue=no):

```
[ 97%] clang++ -o bin/godot.x11.opt.tools.64.llvm -pipe -rdynamic -rdynamic platform/x11/godot_x11.x11.opt.tools.64.llvm.o platform/x11/context_gl_x11.x11.opt.tools.64.llvm.o platform/x11/crash_handler_x11.x11.opt.tools.64.llvm.o platform/x11/os_x11.x11.opt.tools.64.llvm.o platform/x11/key_mapping_x11.x11.opt.tools.64.llvm.o platform/x11/joypad_linux.x11.opt.tools.64.llvm.o platform/x11/power_x11.x11.opt.tools.64.llvm.o -L/usr/lib main/libmain.x11.opt.tools.64.llvm.a main/tests/libtests.x11.opt.tools.64.llvm.a modules/libmodules.x11.opt.tools.64.llvm.a drivers/libdrivers.x11.opt.tools.64.llvm.a editor/libeditor.x11.opt.tools.64.llvm.a scene/libscene.x11.opt.tools.64.llvm.a servers/libservers.x11.opt.tools.64.llvm.a core/libcore.x11.opt.tools.64.llvm.a modules/svg/libsvg_builtin.x11.opt.tools.64.llvm.a -lX11 -lXcursor -lXinerama -lXrandr -lfreetype -lpng16 -lasound -lpulse-simple -lpulse -lz -lGL -lmono-2.0 -lm -lrt -ldl -lpthread modules/recast/librecast_builtin.x11.opt.tools.64.llvm.a
[100%] progress_finish(["progress_finish"], [])
[100%] modules/libmodules.x11.opt.tools.64.llvm.a(gd_mono.x11.opt.tools.64.llvm.o): In function `_register_internal_calls':
/home/user/godot/modules/mono/mono_wrapper/gd_mono.cpp:233: undefined reference to `GodotSharpBuilds::_register_internal_calls()'
modules/libmodules.x11.opt.tools.64.llvm.a(gd_mono.x11.opt.tools.64.llvm.o): In function `GDMono::_register_internal_calls()':
/home/user/godot/modules/mono/mono_wrapper/gd_mono.cpp:233: undefined reference to `GodotSharpBuilds::_register_internal_calls()'
modules/libmodules.x11.opt.tools.64.llvm.a(csharp_script.x11.opt.tools.64.llvm.o): In function `gdsharp_editor_init_callback()':
/home/user/godot/modules/mono/csharp_script.cpp:86: undefined reference to `GodotSharpEditor::GodotSharpEditor(EditorNode*)'
modules/libmodules.x11.opt.tools.64.llvm.a(csharp_script.x11.opt.tools.64.llvm.o): In function `CSharpLanguage::init()':
/home/user/godot/modules/mono/csharp_script.cpp:102: undefined reference to `BindingsGenerator::handle_cmdline_args(List<String, DefaultAllocator> const&)'
modules/libmodules.x11.opt.tools.64.llvm.a(csharp_script.x11.opt.tools.64.llvm.o): In function `CSharpLanguage::open_in_external_editor(Ref<Script> const&, int, int)':
/home/user/godot/modules/mono/csharp_script.cpp:573: undefined reference to `MonoDevelopInstance::execute(String const&)'
/home/user/godot/modules/mono/csharp_script.cpp:570: undefined reference to `MonoDevelopInstance::MonoDevelopInstance(String const&)'
modules/libmodules.x11.opt.tools.64.llvm.a(csharp_script.x11.opt.tools.64.llvm.o): In function `get_singleton':
/home/user/godot/modules/mono/editor/godotsharp_editor.h:61: undefined reference to `GodotSharpEditor::singleton'
modules/libmodules.x11.opt.tools.64.llvm.a(csharp_script.x11.opt.tools.64.llvm.o): In function `ResourceFormatSaverCSharpScript::save(String const&, Ref<Resource> const&, unsigned int)':
/home/user/godot/modules/mono/csharp_script.cpp:1796: undefined reference to `CSharpProject::add_item(String const&, String const&, String const&)'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.x11.opt.tools.64.llvm] Error 1
scons: building terminated because of errors.
```

**Comment by NathanWarden** [comment]
@tagcup You'll need to reset Godot back to f577efd for the moment to get it to build.

**Comment by NathanWarden** [comment]
@tagcup Rather, commit 5195935, oops :)

**Comment by EReeves** [comment]
I have the same issue on Godot commit 5195935, GodotSharp 826eddb. With a blank project.
Here's the log.
https://gist.github.com/EReeves/d30389a14f31d736f0d42e4b49683ab5

**Comment by neikeq** [comment]
0654950 fixes the build errors. You will need latest Godot master to compile.

**Comment by akien-mga** [comment]
> 0654950 fixes the build errors. You will need latest Godot master to compile.

Though note that current master doesn't build on MSVC, should be fixed tonight.

**Comment by MadIcecream** [comment]
The `Create C# Solution` button is still crashing godot in 0654950215d87ff73a78d54541faa167f369392c, I built it with the latest godot commit.

**Comment by ghost** [comment]
Just pulled godot & godotsharp, compiled and tested; it is still crashing.

Crash happens in both release_debug and debug with clang. Tried with gcc, same.

```
Thread 1 "godot.x11.tools" received signal SIGSEGV, Segmentation fault.
0x0000555556879e57 in Set<RID_Data*, Comparator<RID_Data*>, DefaultAllocator>::find (this=0x55555a3bf8d0, p_value=@0x7fffff908090: 0x55555abb54b0) at core/set.h:513
513                     const Element *res = _find(p_value);
(gdb) bt
#0  0x0000555556879e57 in Set<RID_Data*, Comparator<RID_Data*>, DefaultAllocator>::find (this=0x55555a3bf8d0, p_value=@0x7fffff908090: 0x55555abb54b0) at core/set.h:513
#1  0x0000555556879e0d in Set<RID_Data*, Comparator<RID_Data*>, DefaultAllocator>::has (this=0x55555a3bf8d0, p_value=@0x7fffff908090: 0x55555abb54b0) at core/set.h:533
#2  0x0000555557df2610 in RID_Owner<Space2DSW>::get (this=0x55555a3bf8c8, p_rid=...) at core/rid.h:154
#3  0x0000555557dead2e in Physics2DServerSW::space_get_direct_state (this=0x55555a3bf770, p_space=...) at servers/physics_2d/physics_2d_server_sw.cpp:269
#4  0x0000555557df9ef2 in Physics2DServerWrapMT::space_get_direct_state (this=0x55555a37f530, p_space=...) at servers/physics_2d/physics_2d_server_wrap_mt.h:118
#5  0x000055555729ba60 in Viewport::_notification (this=0x55555aba7880, p_what=16) at scene/main/viewport.cpp:497
#6  0x00005555572b9d47 in Viewport::_notificationv (this=0x55555aba7880, p_notification=16, p_reversed=false) at ./scene/main/viewport.h:89
#7  0x00005555580c4822 in Object::notification (this=0x55555aba7880, p_notification=16, p_reversed=false) at core/object.cpp:849
#8  0x0000555557261bb3 in SceneTree::_notify_group_pause (this=0x55555ab77e80, p_group=..., p_notification=16) at scene/main/scene_tree.cpp:911
#9  0x000055555726159f in SceneTree::iteration (this=0x55555ab77e80, p_time=0.0166666675) at scene/main/scene_tree.cpp:454
#10 0x0000555556286ebe in Main::iteration () at main/main.cpp:1630
#11 0x00005555569b54de in ProgressDialog::task_step (this=0x55555c67d460, p_task=..., p_state=..., p_step=-1, p_force_redraw=true) at editor/progress_dialog.cpp:204
#12 0x0000555556a585b1 in EditorNode::progress_task_step (p_task=..., p_state=..., p_step=-1, p_force_refresh=true) at editor/editor_node.cpp:3274
#13 0x00005555563dd762 in EditorProgress::step (this=0x7fffff90a278, p_state=..., p_step=-1, p_force_refresh=true) at ./editor/editor_node.h:792
#14 0x0000555556408bbe in GodotSharpEditor::_create_project_solution (this=0x55555e52ba50) at modules/mono/editor/godotsharp_editor.cpp:63
#15 0x00005555564097e0 in GodotSharpEditor::_menu_option_pressed (this=0x55555e52ba50, p_id=0) at modules/mono/editor/godotsharp_editor.cpp:120
#16 0x000055555640ca7f in MethodBind1<GodotSharpEditor, int>::call (this=0x55555e58ae70, p_object=0x55555e52ba50, p_args=0x7fffff90a5c0, p_arg_count=1, r_error=...)
    at core/method_bind.gen.inc:815
#17 0x00005555580c864c in Object::call (this=0x55555e52ba50, p_method=..., p_args=0x7fffff90a5c0, p_argcount=1, r_error=...) at core/object.cpp:839
#18 0x00005555580bbe78 in MessageQueue::_call_function (this=0x555559b17fc0, p_target=0x55555e52ba50, p_func=..., p_args=0x7ffff7e7b038, p_argcount=1, p_show_error=true)
    at core/message_queue.cpp:259
#19 0x00005555580bc165 in MessageQueue::flush (this=0x555559b17fc0) at core/message_queue.cpp:304
#20 0x00005555572615c9 in SceneTree::iteration (this=0x55555ab77e80, p_time=0.0166666675) at scene/main/scene_tree.cpp:456
#21 0x0000555556286ebe in Main::iteration () at main/main.cpp:1630
#22 0x00005555569b54de in ProgressDialog::task_step (this=0x55555c67d460, p_task=..., p_state=..., p_step=-1, p_force_redraw=true) at editor/progress_dialog.cpp:204
#23 0x0000555556a585b1 in EditorNode::progress_task_step (p_task=..., p_state=..., p_step=-1, p_force_refresh=true) at editor/editor_node.cpp:3274
#24 0x00005555563dd762 in EditorProgress::step (this=0x7fffff90ac58, p_state=..., p_step=-1, p_force_refresh=true) at ./editor/editor_node.h:792
#25 0x0000555556408bbe in GodotSharpEditor::_create_project_solution (this=0x55555e52ba50) at modules/mono/editor/godotsharp_editor.cpp:63
#26 0x00005555564097e0 in GodotSharpEditor::_menu_option_pressed (this=0x55555e52ba50, p_id=0) at modules/mono/editor/godotsharp_editor.cpp:120
#27 0x000055555640ca7f in MethodBind1<GodotSharpEditor, int>::call (this=0x55555e58ae70, p_object=0x55555e52ba50, p_args=0x7fffff90afa0, p_arg_count=1, r_error=...)
    at core/method_bind.gen.inc:815
#28 0x00005555580c864c in Object::call (this=0x55555e52ba50, p_method=..., p_args=0x7fffff90afa0, p_argcount=1, r_error=...) at core/object.cpp:839
#29 0x00005555580bbe78 in MessageQueue::_call_function (this=0x555559b17fc0, p_target=0x55555e52ba50, p_func=..., p_args=0x7ffff7e7b038, p_argcount=1, p_show_error=true)
    at core/message_queue.cpp:259
#30 0x00005555580bc165 in MessageQueue::flush (this=0x555559b17fc0) at core/message_queue.cpp:304
#31 0x00005555572615c9 in SceneTree::iteration (this=0x55555ab77e80, p_time=0.0166666675) at scene/main/scene_tree.cpp:456
#32 0x0000555556286ebe in Main::iteration () at main/main.cpp:1630
#33 0x00005555569b54de in ProgressDialog::task_step (this=0x55555c67d460, p_task=..., p_state=..., p_step=-1, p_force_redraw=true) at editor/progress_dialog.cpp:204
```

(truncated backtrace because it just goes on and on)

**Comment by EReeves** [comment]
the backtrace is the same for me as with teacup.

Godot dc18b8d 
GodotSharp ff4b1a4

**Comment by neikeq** [comment]
`EditorProgress` is too hackish. Apparently, it can't be used from a method called via `call_deferred`. In fact, `EditorProgress` was the cause of this issue in the first place... Can you check if e6d8b79 fixed it?

**Comment by EReeves** [comment]
Yep, I'll update when the build is done.

**Comment by EReeves** [comment]
That seems to have fixed it. Thanks!

**Comment by MadIcecream** [comment]
Yes, the bug is fixed =)

**Comment by ghost** [comment]
Yep
